---
title: "Predict Placental Cell Composition"
output: 
    rmarkdown::html_vignette:
        df_print: "kable"
        fig_caption: FALSE
        toc: TRUE
pkgdown:
    as_is: true
vignette: >
    %\VignetteIndexEntry{Predict Placental Cell Composition}
    %\VignetteEncoding{UTF-8}
    %\VignetteEngine{knitr::rmarkdown}
editor_options: 
    chunk_output_type: console
---

### Installation


```r
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("planet")
```

### Set up

To infer cell composition on placental villi DNAm samples, we can use the
reference cpgs identified in [3]. These are provided in this package as
`plCellCpGsThird` and `plCellCpGsFirst` for third trimester (term) and
first trimester samples, respectively.

In this example we are using term villi DNAm data, so we first load the 
reference cpgs `plCellCpGsThird`. This is a data frame of 600 cpgs, with 
mean methylation levels for each cell type.





```r
# cell deconvolution packages
# library(minfi) # currently not installable on R devel
library(EpiDISH)

# data wrangling and plotting
library(dplyr)
library(ggplot2)
library(tidyr)

library(planet)

# load example data
data("plBetas")
data("plCellCpGsThird")
head(plCellCpGsThird)
#>            Trophoblasts   Stromal  Hofbauer Endothelial
#> cg10590657    0.1014098 0.9345796 0.8655285   0.8963641
#> cg14923398    0.1282030 0.8902107 0.9036769   0.9383641
#> cg05348366    0.1305697 0.9519820 0.8803082   0.9065136
#> cg17907628    0.1215249 0.9278777 0.8727841   0.8914412
#> cg26799656    0.1259953 0.9482014 0.8803863   0.8791004
#> cg11862144    0.1561991 0.9430855 0.9114967   0.9341671
#>                 nRBC Syncytiotrophoblast
#> cg10590657 0.8448382          0.05460441
#> cg14923398 0.9508709          0.05383193
#> cg05348366 0.9278057          0.06546727
#> cg17907628 0.9143601          0.05325227
#> cg26799656 0.9010419          0.06823985
#> cg11862144 0.9647331          0.06044207
```

After our reference cpg data is loaded, we can estimate cell composition by
applying either the Constrained Projection approach implemented by the R 
packages minfi or EpiDISH, or a non-constrained approach by EpiDish.

#### Minfi


```r
houseman_estimates <- minfi:::projectCellType(
    plBetas[rownames(plCellCpGsThird), ],
    plCellCpGsThird,
    lessThanOne = FALSE
)

head(houseman_estimates)
```

#### EpiDish


```r
# robust partial correlations
epidish_RPC <- epidish(
    beta.m = plBetas[rownames(plCellCpGsThird), ],
    ref.m = plCellCpGsThird,
    method = "RPC"
)

# CIBERSORT
epidish_CBS <- epidish(
    beta.m = plBetas[rownames(plCellCpGsThird), ],
    ref.m = plCellCpGsThird,
    method = "CBS"
)

# constrained projection (houseman 2012)
epidish_CP <- epidish(
    beta.m = plBetas[rownames(plCellCpGsThird), ],
    ref.m = plCellCpGsThird,
    method = "CP"
)
```

### Compare

We can compare the different cell composition estimates.


```r
data("plColors")

# bind estimate data frames and reshape for plotting
bind_rows(
    #houseman_estimates %>% as.data.frame() %>% 
    #    mutate(algorithm = "CP (Houseman)"),
    epidish_RPC$estF %>% as.data.frame() %>% mutate(algorithm = "RPC"),
    epidish_CBS$estF %>% as.data.frame() %>% mutate(algorithm = "CBS"),
    epidish_CP$estF %>% as.data.frame() %>% mutate(algorithm = "CP (EpiDISH)")
) %>%
    mutate(sample = rep(rownames(houseman_estimates), 4)) %>%
    as_tibble() %>%
    pivot_longer(
        cols = -c(algorithm, sample),
        names_to = "component",
        values_to = "estimate"
    ) %>%

    # relevel for plot
    mutate(component = factor(component,
        levels = c(
            "nRBC", "Endothelial", "Hofbauer",
            "Stromal", "Trophoblasts",
            "Syncytiotrophoblast"
        )
    )) %>%

    # plot
    ggplot(aes(x = sample, y = estimate, fill = component)) +
    geom_bar(stat = "identity") +
    facet_wrap(~algorithm, ncol = 1) +
    scale_fill_manual(values = plColors) +
    scale_y_continuous(
        limits = c(-0.1, 1.1), breaks = c(0, 0.5, 1),
        labels = scales::percent
    ) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
    coord_cartesian(ylim = c(0, 1)) +
    labs(x = "", fill = "")
#> Error: Problem with `mutate()` input `sample`.
#> x error in evaluating the argument 'x' in selecting a method for function 'rownames': object 'houseman_estimates' not found
#> i Input `sample` is `rep(rownames(houseman_estimates), 4)`.
```

Some notes:

* Normalize your data with `minfi::preprocessNoob`
* Use all cell CpGs, if some are missing, estimates may vary
* If your samples have been processed in a particular manner, (e.g. sampling 
from maternal side) expect cell composition to reflect that

### References

1. [Victor Yuan, Desmond Hui, Yifan Yin et al. Cell-specific Characterization 
of the Placental Methylome, 29 October 2020, PREPRINT (Version 3) available at
Research Square](https://www.researchsquare.com/article/rs-38223/v3)

### Session Info


```r
sessionInfo()
#> R Under development (unstable) (2020-12-18 r79646)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19042)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_Canada.1252 
#> [2] LC_CTYPE=English_Canada.1252   
#> [3] LC_MONETARY=English_Canada.1252
#> [4] LC_NUMERIC=C                   
#> [5] LC_TIME=English_Canada.1252    
#> 
#> attached base packages:
#> [1] stats4    parallel  stats     graphics  grDevices utils    
#> [7] datasets  methods   base     
#> 
#> other attached packages:
#>  [1] planet_0.99.1               tidyr_1.1.2                
#>  [3] dplyr_1.0.2                 EpiDISH_2.7.0              
#>  [5] bumphunter_1.33.0           locfit_1.5-9.4             
#>  [7] iterators_1.0.13            foreach_1.5.1              
#>  [9] Biostrings_2.59.2           XVector_0.31.1             
#> [11] SummarizedExperiment_1.21.1 Biobase_2.51.0             
#> [13] MatrixGenerics_1.3.0        matrixStats_0.57.0         
#> [15] GenomicRanges_1.43.1        GenomeInfoDb_1.27.3        
#> [17] IRanges_2.25.6              S4Vectors_0.29.6           
#> [19] BiocGenerics_0.37.0         ggplot2_3.3.3              
#> 
#> loaded via a namespace (and not attached):
#>  [1] nlme_3.1-151              bitops_1.0-6             
#>  [3] bit64_4.0.5               filelock_1.0.2           
#>  [5] progress_1.2.2            httr_1.4.2               
#>  [7] rprojroot_2.0.2           tools_4.1.0              
#>  [9] doRNG_1.8.2               utf8_1.1.4               
#> [11] R6_2.5.0                  mgcv_1.8-33              
#> [13] DBI_1.1.0                 colorspace_2.0-0         
#> [15] withr_2.3.0               tidyselect_1.1.0         
#> [17] prettyunits_1.1.1         bit_4.0.4                
#> [19] curl_4.3                  compiler_4.1.0           
#> [21] cli_2.2.0                 xml2_1.3.2               
#> [23] DelayedArray_0.17.7       labeling_0.4.2           
#> [25] rtracklayer_1.51.3        scales_1.1.1             
#> [27] quadprog_1.5-8            askpass_1.1              
#> [29] rappdirs_0.3.1            stringr_1.4.0            
#> [31] digest_0.6.27             Rsamtools_2.7.0          
#> [33] rmarkdown_2.6             htmltools_0.5.0          
#> [35] pkgconfig_2.0.3           sparseMatrixStats_1.3.2  
#> [37] highr_0.8                 dbplyr_2.0.0             
#> [39] rlang_0.4.9               rstudioapi_0.13          
#> [41] RSQLite_2.2.1             DelayedMatrixStats_1.13.2
#> [43] farver_2.0.3              BiocIO_1.1.2             
#> [45] generics_0.1.0            BiocParallel_1.25.2      
#> [47] RCurl_1.98-1.2            magrittr_2.0.1           
#> [49] GenomeInfoDbData_1.2.4    Matrix_1.3-2             
#> [51] fansi_0.4.1               Rcpp_1.0.5               
#> [53] munsell_0.5.0             lifecycle_0.2.0          
#> [55] stringi_1.5.3             yaml_2.2.1               
#> [57] MASS_7.3-53               zlibbioc_1.37.0          
#> [59] BiocFileCache_1.15.1      grid_4.1.0               
#> [61] blob_1.2.1                crayon_1.3.4             
#> [63] lattice_0.20-41           splines_4.1.0            
#> [65] GenomicFeatures_1.43.3    hms_0.5.3                
#> [67] knitr_1.30                pillar_1.4.7             
#> [69] rjson_0.2.20              rngtools_1.5             
#> [71] codetools_0.2-18          biomaRt_2.47.1           
#> [73] XML_3.99-0.5              glue_1.4.2               
#> [75] evaluate_0.14             vctrs_0.3.6              
#> [77] locfdr_1.1-8              gtable_0.3.0             
#> [79] openssl_1.4.3             purrr_0.3.4              
#> [81] assertthat_0.2.1          xfun_0.19                
#> [83] restfulr_0.0.13           e1071_1.7-4              
#> [85] class_7.3-17              tibble_3.0.4             
#> [87] GenomicAlignments_1.27.2  AnnotationDbi_1.53.0     
#> [89] memoise_1.1.0             ellipsis_0.3.1           
#> [91] here_1.0.1
```
